backend:
  name: git-gateway
  repo: damiandominella/architetti
  branch: main

media_folder: static/img
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  - name: "project" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    folder: "content/project" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "image",
          required: false,
          allow_multiple: true
      }
      - { label: "Body", name: "body", widget: "markdown" }
